FROM node:12.18-alpine

RUN apk add --no-cache bash

RUN npm install nodemon -g

WORKDIR /home/whishlist

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

CMD [ "nodemon", "src/index.js" ]
