FROM node:12.18-alpine

RUN apk add --no-cache bash

RUN npm install mocha -g

WORKDIR /home/whishlist

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

CMD [ "mocha", "tests/**/*.test.js", "--reporter", "spec" ]
